"""add request fingerprint to orders

Revision ID: 2f0b69c7827c
Revises: 08cbd923c71c
Create Date: 2026-08-20 14:05:42.630401

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f0b69c7827c"
down_revision: str | Sequence[str] | None = "08cbd923c71c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        schema="orders",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "request_fingerprint", schema="orders")
    # ### end Alembic commands ###
