"""create orders

Revision ID: 4400889f9841
Revises: 55819606190c
Create Date: 2026-08-12 11:49:57.049438

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4400889f9841"
down_revision: str | Sequence[str] | None = "55819606190c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("order_number", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','CONFIRMED','RESERVED','RESERVATION_FAILED','CANCELLED')",
            name=op.f("ck_orders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["orders.customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["orders.sales_entities.id"],
            name=op.f("fk_orders_entity_id_sales_entities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "entity_id",
            "idempotency_key",
            name=op.f("uq_orders_entity_id_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "entity_id", "order_number", name=op.f("uq_orders_entity_id_order_number")
        ),
        schema="orders",
    )
    op.create_index(
        op.f("ix_orders_customer_id"),
        "orders",
        ["customer_id"],
        unique=False,
        schema="orders",
    )
    op.create_index(
        op.f("ix_orders_entity_id"),
        "orders",
        ["entity_id"],
        unique=False,
        schema="orders",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_entity_id"), table_name="orders", schema="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders", schema="orders")
    op.drop_table("orders", schema="orders")
    # ### end Alembic commands ###
