"""create order_lines

Revision ID: 58332eec8633
Revises: 4400889f9841
Create Date: 2026-08-12 11:53:20.246761

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58332eec8633"
down_revision: str | Sequence[str] | None = "4400889f9841"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["orders.items.id"], name=op.f("fk_order_lines_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.orders.id"],
            name=op.f("fk_order_lines_order_id_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
        sa.UniqueConstraint("order_id", "item_id", name=op.f("uq_order_lines_order_id_item_id")),
        schema="orders",
    )
    op.create_index(
        op.f("ix_order_lines_item_id"),
        "order_lines",
        ["item_id"],
        unique=False,
        schema="orders",
    )
    op.create_index(
        op.f("ix_order_lines_order_id"),
        "order_lines",
        ["order_id"],
        unique=False,
        schema="orders",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_lines_order_id"), table_name="order_lines", schema="orders")
    op.drop_index(op.f("ix_order_lines_item_id"), table_name="order_lines", schema="orders")
    op.drop_table("order_lines", schema="orders")
    # ### end Alembic commands ###
