"""create customers

Revision ID: b901bbc1cad1
Revises: b6055d588970
Create Date: 2026-08-11 11:46:18.416829

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b901bbc1cad1"
down_revision: str | Sequence[str] | None = "b6055d588970"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["orders.sales_entities.id"],
            name=op.f("fk_customers_entity_id_sales_entities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("entity_id", "code", name=op.f("uq_customers_entity_id_code")),
        schema="orders",
    )
    op.create_index(
        op.f("ix_customers_entity_id"), "customers", ["entity_id"], unique=False, schema="orders"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_entity_id"), table_name="customers", schema="orders")
    op.drop_table("customers", schema="orders")
    # ### end Alembic commands ###
