"""create inventory_reservations

Revision ID: 8425f123724d
Revises: 300d308c3e81
Create Date: 2026-08-16 15:49:51.088198

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8425f123724d"
down_revision: str | Sequence[str] | None = "300d308c3e81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_event", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RELEASED')", name=op.f("ck_inventory_reservations_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id", "item_id"],
            ["inventory.inventory.entity_id", "inventory.inventory.item_id"],
            name=op.f("fk_inventory_reservations_entity_id_inventory"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
        schema="inventory",
    )
    op.create_index(
        op.f("ix_inventory_reservations_item_id"),
        "inventory_reservations",
        ["item_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        op.f("ix_inventory_reservations_order_id"),
        "inventory_reservations",
        ["order_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        "uq_inventory_reservations_active_order_item",
        "inventory_reservations",
        ["order_id", "item_id"],
        unique=True,
        schema="inventory",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_inventory_reservations_active_order_item",
        table_name="inventory_reservations",
        schema="inventory",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(
        op.f("ix_inventory_reservations_order_id"),
        table_name="inventory_reservations",
        schema="inventory",
    )
    op.drop_index(
        op.f("ix_inventory_reservations_item_id"),
        table_name="inventory_reservations",
        schema="inventory",
    )
    op.drop_table("inventory_reservations", schema="inventory")
    # ### end Alembic commands ###
